### ISSUE TITLE
Print Stats blank after fresh install

### ISSUE THREAD

**Issue by beecroftst** [amsbr/OctoPrint-Stats#10]
![2017-11-20_21-47-47](https://user-images.githubusercontent.com/33855747/33056808-843df392-ce3c-11e7-93ee-7acbc2753a90.jpg)

Now sure what the issue is, installed using Octoprint Plugin manager, with a couple other plugins, restarted Octoprint and the Print stats are blank.

Any ideas?

Thanks,
Steve

**Comment by amsbr** [comment]
Hi Steve,

please send details of your OctoPrint version. I will prepare a new release in some days.

**Comment by Erutan409** [comment]
I'm having the same issue.  Is there any ETA on an update for this?  Seemed to stop working all of a sudden after a recent upgrade.

**Comment by amsbr** [comment]
Hi all,

I building a new version with MongoDB, for correct all bugs and add new features. I intend to release this on some days.

Thank you

**Comment by Erutan409** [comment]
I uninstalled a couple plugins.  After doing so, the issue corrected itself.  One of them I recall was the YouTube Live plugin.  Don't know if this affecting other people.  Thought I'd share.

**Comment by mathisoneric** [comment]
I'm having the same issue. I installed your plugin and see the same blank screen as the screenshot in the first post.

I'm using OctoPrint 1.3.9.

**Comment by KenwoodFox** [comment]
I too am having this issue, Hope this can be fixed soon.

Using OctoPrint 1.3.9

**Comment by KenwoodFox** [comment]
Im using the cost plugin, and the above image also uses the cost plugin, maybe i will try uninstalling cost

**Comment by amsbr** [comment]
Hi @beecroftst @Erutan409 @KenwoodFox!

please try the renewed version 2.0.0
