### ISSUE TITLE
Successful prints not recorded

### ISSUE THREAD

**Issue by keithellis74** [amsbr/OctoPrint-Stats#11]
Successful prints are not being recorded.  It does not record any data for "Prints" or "Print Complete"

For each upload I have printed. So it should be showing lots of prints and prints completed.

![print status](https://user-images.githubusercontent.com/6196195/35175970-3e3bebae-fd6e-11e7-815a-65e6c1480ceb.png)

**Comment by amsbr** [comment]
Hi @keithellis74,

I will prepare a new release in some days to correct this. Thank you for report.

**Comment by amsbr** [comment]
Hi @keithellis74!

The new release, 2.0.0, fix several bugs of version 1. Try it.
