### ISSUE TITLE
Stats only partially shown

### ISSUE THREAD

**Issue by tiebie** [amsbr/OctoPrint-Stats#12]
Hi,

I installed a new instance of OctoPrint in January. Everything worked fine 'till February, since then the stats are only partially displayed.

![print stats](https://user-images.githubusercontent.com/36410210/36099021-6ea51176-1001-11e8-907b-0f3476c6e879.jpg)

The power stats are still displayed and are updated after each print. The other stats are missing. All usual remedies (reboot...) do not solve the problem.

I'm running the **exact same config** on a second printer and it works fine...

Config:
OctoPrint 1.3.6 on Raspberry Pi 2
Printer Prusa i3 MK2S

Addons:
Printer Stats 1.0.0
AstroPrint 1.0.2
DetailedPrograss 0.1,4
Themeify 1.1.0

**Comment by amsbr** [comment]
Hi @tiebie!

The new release, 2.0.0, fix several bugs of version 1. Try it.
