### ISSUE TITLE
Z-index issues with Tempsgraph

### ISSUE THREAD

**Issue by rameden** [amsbr/OctoPrint-Stats#6]
If you have both Tempsgraph and OctoPrint-Stats installed when on the Octoprint homepage trying to hover over the dropdown will result in you not being able to click on Printer Statistics due to it being behind the Tempsgraph items. 

<img width="476" alt="z-indexissue" src="https://cloud.githubusercontent.com/assets/1105847/24592204/c02ead64-17e0-11e7-93d0-0aa37c84794f.PNG">

**Comment by amsbr** [comment]
Hi @rameden,

I test this, problem occur with Tempsgraph and Octoprint template, not related with OctoPrint-Stats.

please contact Tempsgraph developer.
